### PR TITLE
Expand documentation regarding RabbitMQ access

### PR DESCRIPTION
**Pull request by itsouvalas**
Quick how to on rabbitmq access and manual backup information.

### CODE REVIEW

**Comment by christian-roggia** [comment]
It should be added that Blacksmith dashboard UI can be retrieved with the command `cf service-brokers`. Otherwise LGTM.

**Comment by itsouvalas** [comment]
`cf service-brokers` does give you the URL as does the `genesis info` against the blacksmith environment, though it doesn't offer the credentials required to access the UI.

**Comment by christian-roggia** [comment]
Correct! Dr. Gao suggested to use for example for demos to hide the credentials while presenting, do you think it's worth adding?

**Comment by itsouvalas** [comment]
Good catch indeed! Given the context of this doc is towards operators in general and although helpful, not specific to a demonstration and the requirement to omit sensitive information, I believe we could omit it favour of brevity.

**Comment by xiujiao** [comment]
We have one issue that we need to fix in future. genesis info gives the ip
of blacksmith even the domain is set for blacksmith. Cf service broker
brokers shows domain name since we fixed register broker addon to use
domain instead of ip if domain is set.
We should list both commands for that reason.
When domain is set, operator should visit blacksmith through domain url
instead of ip

**Comment by itsouvalas** [comment]
Thank you for bringing this to my attention @xiujiao. I went ahead and added the information to access the _web url_ using the FQDN as returned by `cf service-brokers`. Also added the `release_notes.md` required for the pending new release.

**Comment by christian-roggia** [comment]
LGTM

**Pull request merged**
